apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-network-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-probe
  template:
    metadata:
      labels:
        app: go-probe
    spec:
      containers:
      - name: probe-container
        image: network-probe:v1
        imagePullPolicy: Never # Important: forces K8s to use the local image
